### ISSUE TITLE
AWS::ECS::Cluster.Tags

### ISSUE THREAD

**Issue by benbridts** [cfntools/cloudformation-gaps#14]
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TagResource.html

**Comment by nuttmeister** [comment]
We have a custom resource for that, if anyone wants to use it it can be found here.
It's written in Go, but there are deploy instructions in the readme.

[https://github.com/dwtechnologies/custom-cf](https://github.com/dwtechnologies/custom-cf)

**Comment by trav-c** [comment]
CloudFormation support for tagging of AWS::ECS::Cluster, AWS::ECS::Service and AWS::ECS::TaskDefinition has been announced

- https://github.com/aws/containers-roadmap/issues/93#issuecomment-501953226
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by benbridts** [comment]
released on June 13, 2019
