### ISSUE TITLE
AWS::ECS::TaskDefinition.ContainerDefinitions.secrets

### ISSUE THREAD

**Issue by jgondron** [cfntools/cloudformation-gaps#19]
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RegisterTaskDefinition.html
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

**Comment by trav-c** [comment]
CloudFormation support for container definition secrets has been announced
- https://github.com/aws/containers-roadmap/issues/97#issuecomment-501953048
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by benbridts** [comment]
released on June 13, 2019
