### ISSUE TITLE
AWS::ECS::TaskDefinition.ContainerDefinitions.secrets

### ISSUE THREAD

**Issue by trav-c** [cfntools/cloudformation-gaps#36]
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-secrets

**Comment by trav-c** [comment]
Looks like there is some progress on this - https://github.com/aws/containers-roadmap/issues/97#issuecomment-495432974

**Comment by trav-c** [comment]
Just noticed that this is actually a duplicate, #19 had already been opened for this same property.

**Comment by benbridts** [comment]
Thanks for the follow-up!
