### ISSUE TITLE
AWS::ECR::Repository.Tags

### ISSUE THREAD

**Issue by trav-c** [cfntools/cloudformation-gaps#41]
ECR Repositories can be tagged with the following API
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_TagResource.html

There is no support for this tagging listed in the CloudFormation documentation for ECR repositories
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html

**Comment by trav-c** [comment]
A feature request has now been submitted to AWS support for this.

**Comment by trav-c** [comment]
Support for tagging ECR repositories via CloudFormation is now available, although it is not mentioned in the release notes, it is confirmed here:
https://github.com/aws/containers-roadmap/issues/93#issuecomment-502164657

And documented here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html

**Comment by benbridts** [comment]
Thanks!
